### ISSUE TITLE
Looking for feedback: Show fallback image if a featured image is found?

### ISSUE THREAD

**Issue by chuckreynolds** [chuckreynolds/WPFBOGP#54]
Lately I've been considering not showing the fallback image if there's a featured image present. Thought is - if you have a featured image it's probably more important than a fallback image and because FB sometimes pulls the image array in different orders - the fallback gets shown sometimes when it should use the featured image.

Open to opinions here.

**Comment by jjeaton** [comment]
I completely agree with that.

I was about to open an issue to ask to have the fallback image loaded last, as [this line](https://github.com/chuckreynolds/WPFBOGP/blob/master/wp-facebook-ogp.php#L188) reverses the array and it gets output first, which seems to result in it getting chosen more often than the other images.

I would suggest two changes:

* Don't load the fallback image if there's a featured image
* Output the fallback image at the end of the list of images, if there isn't a featured image.

Happy to submit a PR if it would help.

**Comment by chuckreynolds** [comment]
@jjeaton make sure you're looking at the `develop` branch. That's where all the new stuff is. Beta 2 is the official last tag but I've got a lot of stuff in there since. So.. look there. 
That array is currently fixed but re: this topic... thinking about taking the fallback out if a featured is found. 

This also means I need to fix the featured issue I found and listed in #53 

Technically is all works and nobody's ever complained but I could try and push that into this next main release or do it as a .1 after the fact. I'd really like to get this puppy out this weekend if I can. :+1:

**Comment by chuckreynolds** [comment]
Okay bear with me here. Sketched this out on my mirror (whiteboard alternative ;) Need to talk it through and add in proper wp code after. 
## NEW FLOW
```
IF forcefallbackimage checkbox is TRUE && fallback image is not empty {
-- echo meta og:image with fallback image url.
done.
ELSEIF is a post, page, or page_for_posts (blog run by a page in settings) && thumbnails are enabled && it has a thumbnail
-- echo meta og:image with featured image url.
done.
ELSEIF { 
  IF is post, page, or frontpage with page_on_front {
    -- run through the content and add to array
  } IF fallback image is not empty {
    -- add fallback image to bottom of array
  }
  test array and output the image array to meta og:image tag(s).
  else after all that shit - nothing is there then output <!-- no images found bro --> warning.
}
```

WHEW..... 
sound good??  cc @jjeaton 
I need a beer

**Comment by chuckreynolds** [comment]
first stab at this rewrite. more to go. in branch `feature/images-overhaul` line 160.
https://github.com/chuckreynolds/WPFBOGP/commit/25f8fa114de2bc8302338edf07071b092efb991f#diff-c8cc0644f3623183b121b88dde0bae39R259

**Comment by jjeaton** [comment]
Your logic here looks sound to me.

**Comment by chuckreynolds** [comment]
2.3.0-beta.3 has it all inclusive. feel free to test: https://github.com/chuckreynolds/WPFBOGP/releases/tag/2.3.0-beta.3
