### ISSUE TITLE
After upgrading to 2.0.12 it is adding trailing slash to url

### ISSUE THREAD

**Issue by cavellblood** [chuckreynolds/WPFBOGP#57]
After I upgraded to 2.0.12 the plugin is adding a trailing slash to the og:url. Like this:
* http://mydomain.com/category/post-name.html/

whereas before it was like this:
* http://mydomain.com/category/post-name.html (no trailing slash)

So now [Facebook debugger] (https://developers.facebook.com/tools/debug/og/object/) says that there is a circular redirect path detected.
![screen shot 2015-06-29 at 4 45 20 pm](https://cloud.githubusercontent.com/assets/727740/8421035/4bf90ee2-1e7e-11e5-94ad-2a7899c15da1.png)

Let me know how I can change this to work how it was before.

Thanks!

**Comment by chuckreynolds** [comment]
Support -> https://wordpress.org/support/plugin/wp-facebook-open-graph-protocol

Regardless of that - you could downgrade to 2.0.11 
Versions on WP too: https://wordpress.org/plugins/wp-facebook-open-graph-protocol/developers/

Closing

**Comment by cavellblood** [comment]
Ok, I didn't look for the support on the plugin page. And didn't think about downgrading. I'll downgrade for now.

Thanks!
